DEFAULT_GRID_SIZE = 10
DEFAULT_GRID_SIZE_MIN = 3
DEFAULT_GRID_SIZE_MAX = 50
DEFAULT_SHOW_COLORS = True

DEFAULT_CONSTANT_MULTIPLIER = 1.0
DEFAULT_CONSTANT_MULTIPLIER_MIN = -100.0
DEFAULT_CONSTANT_MULTIPLIER_MAX = 100.0
DEFAULT_CONSTANT_MULTIPLIER_STEP = 0.1
DEFAULT_CONSTANT_MULTIPLIER_DECIMALS = 2

DEFAULT_IMAGE_GRID_CELL_SIZE = 30
DEFAULT_KERNEL_GRID_CELL_SIZE = 45

DEFAULT_IMAGE_WIDTH = 10
DEFAULT_IMAGE_HEIGHT = 10
DEFAULT_WHITE_PIXEL = 255
DEFAULT_BLACK_PIXEL = 0
